
export const PLATFORMS = [
  { id: 'YOUTUBE', label: 'YouTube Shorts', icon: '🎬' },
  { id: 'TIKTOK', label: 'TikTok Viral', icon: '🎵' },
  { id: 'IG', label: 'IG Reels', icon: '📸' },
  { id: 'LINKEDIN', label: 'LinkedIn Authority', icon: '💼' }
] as const;

export const TRANSLATIONS: Record<string, any> = {
  IT: {
    tagline: "Senior Master Audit",
    mainTitle: "MASTER.",
    mainTitleRed: "AUDIT",
    login: "Accedi",
    logout: "Esci",
    register: "Registrati",
    emailPlaceholder: "Email master...",
    passwordPlaceholder: "Password segreta...",
    startNow: "Inizia Ora",
    authTitle: "Accesso Master",
    modeVideo: "Analisi Video",
    modeIdea: "Concept Dirompente",
    uploadLabel: "Carica Video per l'Audit",
    ideaLabel: "Genera Strategia d'Urto",
    ideaPlaceholder: "Scrivi anche solo una parola... l'IA creerà il caos virale.",
    imageUploadLabel: "Riferimento Visivo",
    removeImage: "Rimuovi",
    creditsLabel: "CREDITI",
    upgradeBtn: "Piani Master",
    processing: "Analisi Senior in corso...",
    encoding: "Codifica Stream...",
    paymentProcessing: "Stripe Secure...",
    paymentSuccess: "Transazione Riuscita!",
    activate: "Acquista Crediti",
    pricingTitle: "UPGRADE ASSETS",
    pricingSub: "Scala la tua autorità con crediti premium",
    errorQuota: "⚠️ Limite raggiunto. Attendi 60 secondi.",
    errorAuth: "❌ Credenziali non valide.",
    errorVideoSize: "Video troppo pesante. Massimo 15MB.",
    errorSelectPlatform: "Seleziona una piattaforma prima di iniziare.",
    errorEmptyIdea: "Inserisci un'idea o un'immagine!",
    translateBtn: "TRADUCI REPORT IN",
    translating: "Traduzione Master...",
    copyBtn: "Copia Testo",
    copied: "Copiato",
    newAudit: "← NUOVO AUDIT",
    unlockStoryboard: "SBLOCCA STORYBOARD TECNICO",
    loadingStoryboard: "PRODUZIONE...",
    closeStoryboard: "Chiudi Storyboard",
    viralScore: "VIRAL POTENTIAL",
    contentStructure: "STRUTTURA DIROMPENTE",
    copywritingTitle: "COPYWRITING IPNOTICO",
    techStoryboard: "STORYBOARD TECNICO",
    visionaryTitle: "Regia Anti-Convenzionale",
    audioStrategy: "Sound Design & Psicologia Sonora",
    scene: "SCENA",
    masterProcessing: "Viral Logic Processing...",
    noAccount: "Non hai un account?",
    hasAccount: "Hai già un account?",
    masterModeOn: "MASTER MODE ATTIVATA",
    masterModeOff: "MASTER MODE DÉSACTIVÉE",
    genError: "ERRORE GENERAZIONE AI",
    back: "Torna Indietro"
  },
  EN: {
    tagline: "Senior Master Audit",
    mainTitle: "MASTER.",
    mainTitleRed: "AUDIT",
    login: "Login",
    logout: "Logout",
    register: "Sign Up",
    emailPlaceholder: "Master email...",
    passwordPlaceholder: "Secret password...",
    startNow: "Start Now",
    authTitle: "Master Access",
    modeVideo: "Video Analysis",
    modeIdea: "Disruptive Concept",
    uploadLabel: "Upload Video for Audit",
    ideaLabel: "Generate Impact Strategy",
    ideaPlaceholder: "Enter even one word... AI will create viral chaos.",
    imageUploadLabel: "Visual Reference",
    removeImage: "Remove",
    creditsLabel: "CREDITS",
    upgradeBtn: "Upgrade",
    processing: "Senior Analysis...",
    encoding: "Stream Encoding...",
    paymentProcessing: "Stripe Secure...",
    paymentSuccess: "Transaction Successful!",
    activate: "Buy Credits",
    pricingTitle: "UPGRADE ASSETS",
    pricingSub: "Scale your authority with premium credits",
    errorQuota: "⚠️ Quota limit. Wait 60 seconds.",
    errorAuth: "❌ Invalid credentials.",
    errorVideoSize: "Video too large. Max 15MB.",
    errorSelectPlatform: "Select a platform first.",
    errorEmptyIdea: "Enter an idea or image!",
    translateBtn: "TRANSLATE REPORT TO",
    translating: "Master Translating...",
    copyBtn: "Copy Text",
    copied: "Copied",
    newAudit: "← NEW AUDIT",
    unlockStoryboard: "UNLOCK TECH STORYBOARD",
    loadingStoryboard: "PRODUCING...",
    closeStoryboard: "Close Storyboard",
    viralScore: "VIRAL POTENTIAL",
    contentStructure: "DISRUPTIVE STRUCTURE",
    copywritingTitle: "HYPNOTIC COPYWRITING",
    techStoryboard: "TECHNICAL STORYBOARD",
    visionaryTitle: "Unconventional Directing",
    audioStrategy: "Sound Design & Psychology",
    scene: "SCENE",
    masterProcessing: "Viral Logic Processing...",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    masterModeOn: "MASTER MODE ON",
    masterModeOff: "MASTER MODE OFF",
    genError: "AI GENERATION ERROR",
    back: "Go Back"
  }
};

export const PRICING_TIERS = [
  { id: 'starter', name: 'Starter Executive', price: '€19', credits: 15, features: ['Audit Video AI', 'Analisi Senior'], popular: false },
  { id: 'pro', name: 'Pro Authority', price: '€49', credits: 50, features: ['Audit Video AI', 'Analisi Senior', 'Storyboard Illimitati'], popular: true },
  { id: 'master', name: 'Master Strategic', price: '€99', credits: 150, features: ['Audit Video AI', 'Analisi Senior', 'Priority Support'], popular: false }
];
