
export const PLATFORMS = [
  { id: 'YOUTUBE', label: 'YouTube Shorts', icon: '🎬' },
  { id: 'TIKTOK', label: 'TikTok Viral', icon: '🎵' },
  { id: 'IG', label: 'IG Reels', icon: '📸' },
  { id: 'LINKEDIN', label: 'LinkedIn Authority', icon: '💼' }
] as const;

export const TRANSLATIONS: Record<string, any> = {
  IT: {
    tagline: "Senior Master Audit",
    mainTitle: "MASTER.",
    mainTitleRed: "AUDIT",
    modeVideo: "Analisi Video",
    modeIdea: "Generatore Idee",
    uploadLabel: "Carica Video per l'Audit",
    ideaLabel: "Genera Strategia Virale",
    ideaPlaceholder: "Descrivi la tua idea virale...",
    creditsLabel: "CREDITI APP",
    upgradeBtn: "UPGRADE",
    processing: "Analisi Senior in corso...",
    encoding: "Codifica Stream...",
    newAudit: "NUOVO AUDIT",
    copyBtn: "COPIA",
    copiedBtn: "COPIATO",
    scriptBtn: "SBLOCCA STORYBOARD TECNICO",
    scriptTitle: "ANALISI TECNICA DELLE SCENE",
    viralScore: "VIRAL SCORE",
    seniorInsight: "SENIOR INSIGHT",
    strategicCopy: "STRATEGIC COPY",
    pricingTitle: "UPGRADE ASSETS",
    pricingSub: "Scegli il tuo piano strategico",
    activate: "ATTIVA ORA",
    errorQuota: "⚠️ IL MASTER È ESAUSTO: Limite giornaliero raggiunto. Torna domani o passa al Pro.",
    errorServer: "⚠️ SERVER SATURO: Riprova tra pochi secondi.",
    errorGeneric: "❌ ERRORE TECNICO: Connessione persa."
  },
  EN: {
    tagline: "Senior Master Audit",
    mainTitle: "MASTER.",
    mainTitleRed: "AUDIT",
    modeVideo: "Video Analysis",
    modeIdea: "Idea Generator",
    uploadLabel: "Upload Video for Audit",
    ideaLabel: "Generate Viral Strategy",
    ideaPlaceholder: "Describe your viral idea...",
    creditsLabel: "APP CREDITS",
    upgradeBtn: "UPGRADE",
    processing: "Senior Analysis in progress...",
    encoding: "Stream Encoding...",
    newAudit: "NEW AUDIT",
    copyBtn: "COPY",
    copiedBtn: "COPIED",
    scriptBtn: "UNLOCK TECHNICAL STORYBOARD",
    scriptTitle: "TECHNICAL SCENE ANALYSIS",
    viralScore: "VIRAL SCORE",
    seniorInsight: "SENIOR INSIGHT",
    strategicCopy: "STRATEGIC COPY",
    pricingTitle: "UPGRADE ASSETS",
    pricingSub: "Choose your strategic plan",
    activate: "ACTIVATE NOW",
    errorQuota: "⚠️ MASTER EXHAUSTED: Daily limit reached. Come back tomorrow or upgrade to Pro.",
    errorServer: "⚠️ SERVER SATURATED: Try again in a few seconds.",
    errorGeneric: "❌ TECHNICAL ERROR: Connection lost."
  },
  ES: {
    tagline: "Senior Master Audit",
    mainTitle: "MASTER.",
    mainTitleRed: "AUDIT",
    modeVideo: "Análisis de Video",
    modeIdea: "Generador de Ideas",
    uploadLabel: "Subir Video para Auditoría",
    ideaLabel: "Generar Estrategia Viral",
    ideaPlaceholder: "Describe tu idea viral...",
    creditsLabel: "CRÉDITOS APP",
    upgradeBtn: "MEJORAR",
    processing: "Análisis Senior en curso...",
    encoding: "Codificando Stream...",
    newAudit: "NUEVA AUDITORÍA",
    copyBtn: "COPIAR",
    copiedBtn: "COPIADO",
    scriptBtn: "DESBLOQUEAR STORYBOARD TÉCNICO",
    scriptTitle: "ANÁLISIS TÉCNICO DE ESCENAS",
    viralScore: "PUNTUACIÓN VIRAL",
    seniorInsight: "VISIÓN SENIOR",
    strategicCopy: "COPIA ESTRATÉGICA",
    pricingTitle: "MEJORAR ACTIVOS",
    pricingSub: "Elige tu plan estratégico",
    activate: "ACTIVAR AHORA",
    errorQuota: "⚠️ MASTER AGOTADO: Límite diario alcanzado. Vuelve mañana o mejora a Pro.",
    errorServer: "⚠️ SERVIDOR SATURADO: Reintenta en unos segundos.",
    errorGeneric: "❌ ERROR TÉCNICO: Conexión perdida."
  },
  FR: {
    tagline: "Senior Master Audit",
    mainTitle: "MASTER.",
    mainTitleRed: "AUDIT",
    modeVideo: "Analyse Vidéo",
    modeIdea: "Générateur d'Idées",
    uploadLabel: "Charger Vidéo pour Audit",
    ideaLabel: "Générer Stratégie Virale",
    ideaPlaceholder: "Décrivez votre idée virale...",
    creditsLabel: "CRÉDITS APP",
    upgradeBtn: "UPGRADE",
    processing: "Analyse Senior en cours...",
    encoding: "Encodage du flux...",
    newAudit: "NOUVEL AUDIT",
    copyBtn: "COPIER",
    copiedBtn: "COPIÉ",
    scriptBtn: "DÉBLOQUER LE STORYBOARD TECHNIQUE",
    scriptTitle: "ANALYSE TECHNIQUE DES SCÈNES",
    viralScore: "SCORE VIRAL",
    seniorInsight: "VISION SENIOR",
    strategicCopy: "COPIE STRATÉGIQUE",
    pricingTitle: "UPGRADE ASSETS",
    pricingSub: "Choisissez votre plan stratégique",
    activate: "ACTIVER MAINTENANT",
    errorQuota: "⚠️ MASTER ÉPUISÉ: Limite quotidienne atteinte. Revenez demain ou passez en Pro.",
    errorServer: "⚠️ SERVEUR SATURÉ: Réessayez dans quelques secondes.",
    errorGeneric: "❌ ERREUR TECHNIQUE: Connexion perdue."
  }
};

export const PRICING_TIERS = [
  { id: 'free', name: 'Starter Executive', price: '€0', credits: 3, features: ['Audit Video AI', 'Analisi Senior'], popular: false },
  { id: 'entry', name: 'Entry Growth', price: '€19', credits: 12, features: ['Audit Video AI', 'Analisi Senior'], popular: false },
  { id: 'medium', name: 'Pro Authority', price: '€49', credits: 40, features: ['Audit Video AI', 'Analisi Senior'], popular: true },
  { id: 'premium', name: 'Master Strategic', price: '€99', credits: 120, features: ['Audit Video AI', 'Analisi Senior'], popular: false }
];
