
export const PLATFORMS = [
  { id: 'YOUTUBE', label: 'YouTube Shorts', icon: '🎬' },
  { id: 'TIKTOK', label: 'TikTok Viral', icon: '🎵' },
  { id: 'IG', label: 'IG Reels', icon: '📸' },
  { id: 'LINKEDIN', label: 'LinkedIn Authority', icon: '💼' }
] as const;

export const TRANSLATIONS: Record<string, any> = {
  IT: {
    tagline: "Senior Master Audit",
    mainTitle: "MASTER.",
    mainTitleRed: "AUDIT",
    login: "Accedi",
    logout: "Esci",
    register: "Registrati",
    emailPlaceholder: "Email master...",
    passwordPlaceholder: "Password segreta...",
    startNow: "Inizia Ora",
    authTitle: "Accesso Master",
    modeVideo: "Analisi Video",
    modeIdea: "Generatore Idee",
    uploadLabel: "Carica Video per l'Audit",
    ideaLabel: "Genera Strategia Virale",
    ideaPlaceholder: "Descrivi la tua idea virale...",
    imageUploadLabel: "Immagine di Riferimento",
    removeImage: "Rimuovi",
    creditsLabel: "CREDITI",
    upgradeBtn: "Piani Master",
    processing: "Analisi Senior in corso...",
    encoding: "Codifica Stream...",
    paymentProcessing: "Stripe Secure...",
    paymentSuccess: "Transazione Riuscita!",
    activate: "Acquista Crediti",
    pricingTitle: "UPGRADE ASSETS",
    pricingSub: "Scala la tua autorità con crediti premium",
    errorQuota: "⚠️ Limite raggiunto. Attendi 60 secondi.",
    errorAuth: "❌ Credenziali non valide.",
    errorVideoSize: "Video troppo pesante. Massimo 15MB.",
    errorSelectPlatform: "Seleziona una piattaforma prima di iniziare.",
    errorEmptyIdea: "Inserisci un'idea o un'immagine!",
    translateBtn: "TRADUCI REPORT IN",
    translating: "Traduzione Master...",
    copyBtn: "Copia Testo",
    copied: "Copiato",
    newAudit: "← NUOVO AUDIT",
    unlockStoryboard: "SBLOCCA STORYBOARD TECNICO",
    loadingStoryboard: "PRODUZIONE...",
    closeStoryboard: "Chiudi Storyboard",
    viralScore: "VIRAL SCORE",
    contentStructure: "STRUTTURA CONTENUTO",
    copywritingTitle: "COPYWRITING STRATEGICO",
    techStoryboard: "STORYBOARD TECNICO",
    visionaryTitle: "Visione Cinematografica (Senior)",
    audioStrategy: "Audio Strategy & SFX",
    scene: "SCENA",
    masterProcessing: "Master AI Logic Processing...",
    noAccount: "Non hai un account?",
    hasAccount: "Hai già un account?",
    masterModeOn: "MASTER MODE ATTIVATA: CREDITI ILLIMITATI",
    masterModeOff: "MASTER MODE DISATTIVATA",
    genError: "ERRORE GENERAZIONE AI",
    back: "Torna Indietro"
  },
  EN: {
    tagline: "Senior Master Audit",
    mainTitle: "MASTER.",
    mainTitleRed: "AUDIT",
    login: "Login",
    logout: "Logout",
    register: "Sign Up",
    emailPlaceholder: "Master email...",
    passwordPlaceholder: "Secret password...",
    startNow: "Start Now",
    authTitle: "Master Access",
    modeVideo: "Video Analysis",
    modeIdea: "Idea Generator",
    uploadLabel: "Upload Video for Audit",
    ideaLabel: "Generate Viral Strategy",
    ideaPlaceholder: "Describe your viral idea...",
    imageUploadLabel: "Reference Image",
    removeImage: "Remove",
    creditsLabel: "CREDITS",
    upgradeBtn: "Upgrade",
    processing: "Senior Analysis...",
    encoding: "Stream Encoding...",
    paymentProcessing: "Stripe Secure...",
    paymentSuccess: "Transaction Successful!",
    activate: "Buy Credits",
    pricingTitle: "UPGRADE ASSETS",
    pricingSub: "Scale your authority with premium credits",
    errorQuota: "⚠️ Quota limit. Wait 60 seconds.",
    errorAuth: "❌ Invalid credentials.",
    errorVideoSize: "Video too large. Max 15MB.",
    errorSelectPlatform: "Select a platform first.",
    errorEmptyIdea: "Enter an idea or image!",
    translateBtn: "TRANSLATE REPORT TO",
    translating: "Master Translating...",
    copyBtn: "Copy Text",
    copied: "Copied",
    newAudit: "← NEW AUDIT",
    unlockStoryboard: "UNLOCK TECH STORYBOARD",
    loadingStoryboard: "PRODUCING...",
    closeStoryboard: "Close Storyboard",
    viralScore: "VIRAL SCORE",
    contentStructure: "CONTENT STRUCTURE",
    copywritingTitle: "STRATEGIC COPYWRITING",
    techStoryboard: "TECHNICAL STORYBOARD",
    visionaryTitle: "Cinematic Vision (Senior)",
    audioStrategy: "Audio Strategy & SFX",
    scene: "SCENE",
    masterProcessing: "Master AI Logic Processing...",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    masterModeOn: "MASTER MODE ON: UNLIMITED CREDITS",
    masterModeOff: "MASTER MODE OFF",
    genError: "AI GENERATION ERROR",
    back: "Go Back"
  },
  DE: {
    tagline: "Senior Master Audit",
    mainTitle: "MASTER.",
    mainTitleRed: "PRÜFUNG",
    login: "Anmelden",
    logout: "Abmelden",
    register: "Registrieren",
    emailPlaceholder: "Master-E-Mail...",
    passwordPlaceholder: "Passwort...",
    startNow: "Jetzt Starten",
    authTitle: "Master-Zugang",
    modeVideo: "Video-Analyse",
    modeIdea: "Ideen-Generator",
    uploadLabel: "Video hochladen",
    ideaLabel: "Strategie generieren",
    ideaPlaceholder: "Beschreibe deine Idee...",
    imageUploadLabel: "Referenzbild",
    removeImage: "Entfernen",
    creditsLabel: "CREDITS",
    upgradeBtn: "Upgrade",
    processing: "Senior-Analyse...",
    encoding: "Kodierung...",
    paymentProcessing: "Stripe Secure...",
    paymentSuccess: "Transaktion erfolgreich!",
    activate: "Credits kaufen",
    pricingTitle: "ASSET-UPGRADE",
    pricingSub: "Skaliere deine Autorität",
    errorQuota: "⚠️ Limit erreicht. 60 Sek. warten.",
    errorAuth: "❌ Ungültige Anmeldedaten.",
    errorVideoSize: "Video zu groß. Max 15MB.",
    errorSelectPlatform: "Wähle eine Plattform.",
    errorEmptyIdea: "Idee oder Bild eingeben!",
    translateBtn: "BERICHT ÜBERSETZEN AUF",
    translating: "Übersetzung...",
    copyBtn: "Kopieren",
    copied: "Kopiert",
    newAudit: "← NEUES AUDIT",
    unlockStoryboard: "STORYBOARD FREISCHALTEN",
    loadingStoryboard: "PRODUKTION...",
    closeStoryboard: "Storyboard schließen",
    viralScore: "VIRAL SCORE",
    contentStructure: "STRUKTUR",
    copywritingTitle: "STRATEGISCHES COPY",
    techStoryboard: "TECH-STORYBOARD",
    visionaryTitle: "Filmische Vision (Senior)",
    audioStrategy: "Audio & SFX Strategie",
    scene: "SZENE",
    masterProcessing: "Master AI Verarbeitung...",
    noAccount: "Kein Konto?",
    hasAccount: "Bereits ein Konto?",
    masterModeOn: "MASTER-MODUS AN",
    masterModeOff: "MASTER-MODUS AUS",
    genError: "AI FEHLER",
    back: "Zurück"
  },
  FR: {
    tagline: "Senior Master Audit",
    mainTitle: "MASTER.",
    mainTitleRed: "AUDIT",
    login: "Connexion",
    logout: "Déconnexion",
    register: "S'inscrire",
    emailPlaceholder: "Email master...",
    passwordPlaceholder: "Mot de passe...",
    startNow: "Démarrer",
    authTitle: "Accès Master",
    modeVideo: "Analyse Vidéo",
    modeIdea: "Générateur d'Idées",
    uploadLabel: "Charger Vidéo",
    ideaLabel: "Générer Stratégie",
    ideaPlaceholder: "Décrivez votre idée...",
    imageUploadLabel: "Image de Référence",
    removeImage: "Supprimer",
    creditsLabel: "CRÉDITS",
    upgradeBtn: "Upgrade",
    processing: "Analyse Senior...",
    encoding: "Encodage...",
    paymentProcessing: "Stripe Secure...",
    paymentSuccess: "Transaction Réussie!",
    activate: "Acheter des Crédits",
    pricingTitle: "UPGRADE ASSETS",
    pricingSub: "Augmentez votre autorité",
    errorQuota: "⚠️ Limite atteinte. Attendez 60s.",
    errorAuth: "❌ Identifiants invalides.",
    errorVideoSize: "Vidéo trop lourde. Max 15MB.",
    errorSelectPlatform: "Sélectionnez une plateforme.",
    errorEmptyIdea: "Entrez une idée ou image!",
    translateBtn: "TRADUIRE LE RAPPORT EN",
    translating: "Traduction...",
    copyBtn: "Copier",
    copied: "Copié",
    newAudit: "← NOUVEL AUDIT",
    unlockStoryboard: "DÉBLOQUER STORYBOARD",
    loadingStoryboard: "PRODUCTION...",
    closeStoryboard: "Fermer Storyboard",
    viralScore: "SCORE VIRAL",
    contentStructure: "STRUCTURE",
    copywritingTitle: "COPYWRITING STRATÉGIQUE",
    techStoryboard: "STORYBOARD TECHNIQUE",
    visionaryTitle: "Vision Cinématique (Senior)",
    audioStrategy: "Stratégie Audio & SFX",
    scene: "SCÈNE",
    masterProcessing: "Traitement Master AI...",
    noAccount: "Pas de compte ?",
    hasAccount: "Déjà un compte ?",
    masterModeOn: "MODE MASTER ACTIVÉ",
    masterModeOff: "MODE MASTER DÉSACTIVÉ",
    genError: "ERREUR GÉNÉRATION AI",
    back: "Retour"
  }
};

export const PRICING_TIERS = [
  { id: 'starter', name: 'Starter Executive', price: '€19', credits: 15, features: ['Audit Video AI', 'Analisi Senior'], popular: false },
  { id: 'pro', name: 'Pro Authority', price: '€49', credits: 50, features: ['Audit Video AI', 'Analisi Senior', 'Storyboard Illimitati'], popular: true },
  { id: 'master', name: 'Master Strategic', price: '€99', credits: 150, features: ['Audit Video AI', 'Analisi Senior', 'Priority Support'], popular: false }
];
